# Generated by Django 4.0.3 on 2022-03-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=128, verbose_name='English')),
                ('uz', models.CharField(max_length=128, verbose_name='Uzbek')),
            ],
        ),
    ]
